language: node_js

node_js:
  - 6

dist: trusty

sudo: required

before_script:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g nyc

script:
  - npm test
  - npm run lint

after_script:
  - "npm install coveralls@^2.11.1 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"